### ISSUE TITLE
PUREE runs unresponsive

### ISSUE THREAD

**Issue by suhuanhou** [skandlab/PUREE#10] opened 2024-04-08 04:28 UTC
R:
write.csv(df_bulk, file = "df_bulk.csv", quote = FALSE, row.names = TRUE)

python:
p = PUREE()
purities_and_logs = p.get_output(dir_dataset.joinpath("df_bulk.csv"), 'HGNC')

![image](https://github.com/skandlab/PUREE/assets/51230435/2a6a63d8-ffbf-4879-bb71-2485bad69afb)

PUREE runs unresponsive！
No information is output！

I uploaded the df_bulk.csv file to the server and soon had the result. So what's wrong with API?
![image](https://github.com/skandlab/PUREE/assets/51230435/90b98a49-b6ed-4dd6-9d12-f7043e74ee43)

Also, can the returned result use the original sample name?

**Comment by erevkov** [comment] 2024-04-10 05:58
Hi, thank you for trying PUREE!

Unfortunately, I am not sure I understand the question, could you clarify it, please? The output looks correct - the purity is predicted for each sample, and the range looks appropriate. The fact that the method does not print out any explicit statement is the expected behavior, you could also check the logs for runtime messages.

For security reasons, the online method will only return anonymized sample names, but the samples are returned in the same order as in the input, so you could easily rename the resulting series with the original index. However, if you would prefer to run the method locally, you could obtain the internal source code of the method for academic use - please contact the corresponding author of the [original paper](https://doi.org/10.1038/s42003-023-04764-8) for that.

**Comment by suhuanhou** [comment] 2024-04-10 06:05
> Hi, thank you for trying PUREE!
> 
> Unfortunately, I am not sure I understand the question, could you clarify it, please? The output looks correct - the purity is predicted for each sample, and the range looks appropriate. The fact that the method does not print out any explicit statement is the expected behavior, you could also check the logs for runtime messages.
> 
> For security reasons, the online method will only return anonymized sample names, but the samples are returned in the same order as in the input, so you could easily rename the resulting series with the original index. However, if you would prefer to run the method locally, you could obtain the internal source code of the method for academic use - please contact the corresponding author of the [original paper](https://doi.org/10.1038/s42003-023-04764-8) for that.

Thank you for your answers!

I tried to use the API method and it ran without an error, but there was no result either. Then I used the same data and analyzed it online to get the results.

I want to be able to run PUREE through API methods.

**Comment by erevkov** [comment] 2024-04-11 07:32
Could you please clarify further what kind of behavior you observe? The `get_output` method from the API should return the purities and the logs in a dictionary, e.g. after running the

```Python3
p = PUREE()
purities_and_logs = p.get_output(expression_matrix_path, 'HGNC')
```
the resulting purities would be stored in the `purities_and_logs['output']` . For example, could you please let us know what is returned in the `purities_and_logs['output']` in your case?

**Comment by suhuanhou** [comment] 2024-04-11 10:55
> Could you please clarify further what kind of behavior you observe? The `get_output` method from the API should return the purities and the logs in a dictionary, e.g. after running the
> 
> ```python
> p = PUREE()
> purities_and_logs = p.get_output(expression_matrix_path, 'HGNC')
> ```
> 
> the resulting purities would be stored in the `purities_and_logs['output']` . For example, could you please let us know what is returned in the `purities_and_logs['output']` in your case?

Unfortunately, no information was generated, no log files. Only a blank tmp_dir directory is created

**Comment by tanmay2893** [comment] 2024-04-16 07:00
Hi,

The most plausible error you might be facing is the error which typically arises when there is a discrepancy between  the gene identifier type and the data format utilized:
`'ERROR: All of the selected genes are missing from the data, exiting... (Did you set the correct gene identifier type (HGNC or ENSEMBL)?)'`

To assist in resolving the issue, we kindly ask you to check the following:

- Please confirm that the gene identifier type you have provided is accurate for the dataset in use. The identifier type should correspond to the HGNC or ENSEMBL nomenclature as applicable to your data.
- We ask that you inspect the purities_and_logs variable in your environment.

1. This variable should consist of two essential keys in case of successful output: `output` and `logs`. These keys are consistently present in our system when there is a successful run. For example:
![image](https://github.com/skandlab/PUREE/assets/5008218/a4d740e0-5b51-4cce-a2ca-8ee25c7309c3)

2. This variable should consist of a tuple containing two elements like `(False, 'ERROR: ...')` in case of an unsuccessful run. For example:
![image](https://github.com/skandlab/PUREE/assets/5008218/8afdf36f-e957-4978-9d34-831bfbd0f7ee)

Should you encounter any difficulties or require further clarification, do not hesitate to reach out.

**Comment by suhuanhou** [comment] 2024-04-25 02:39
Thank you for your careful answers! But take note of what I've described.

No files were produced, no error messages, no log files, nothing.

When I analyzed the same data on the web, it worked, proving that there was no problem with the data format and the gene name.


![image](https://github.com/skandlab/PUREE/assets/51230435/1ae8f587-2017-49b8-b100-a38c4591d481)

**Comment by tanmay2893** [comment] 2024-05-02 07:50
Thank you for providing the output of `purities_and_logs`. We see that according to the returned tuple, the function fails due to the PosixPath object supplied as an input for the file path, whereas the `.get_output` method expects a string path input. Could you please try using a string path format such as `'/home/user/...'` as the input for the file path? Please don't hesitate to reach out if further assistance is needed.

**Comment by tanmay2893** [comment] 2024-08-06 06:30
We have not received any updates or further information on this issue for some time now. To keep our issue tracker focused and up-to-date, we will be closing this issue. If you believe this issue is still relevant or if you have additional details to provide, please feel free to reopen the issue.

**Closed by tanmay2893** 2024-08-06 06:30 UTC
