### ISSUE TITLE
BASE URL doesn't respond

### ISSUE THREAD

**Issue by younsoo4883** [skandlab/PUREE#3] opened 2023-06-19 06:12 UTC
Dear contributors

Hi, I've found the PUREE article and got fastinated on this tool and I'm happy to open the first issue. 
I was trying to use my tumor RNAseq samples to estimate tumor purity using python api but the BASE URL that you wrote in puree_api.py didn't properly work. 

<img width="827" alt="image" src="https://github.com/skandlab/PUREE/assets/75415666/12c4d30c-7010-42d4-8a5f-f59ad5c68d7a">

I got above internal server error when I run p.get_output("PUREE_input.tsv", "ENSEMBL").
(Your web version is not available as well, I guess?)

Would you give a help?
Thanks a lot in advance.

Best regards,
Younsoo Kang

**Comment by erevkov** [comment] 2023-06-20 05:09
Hi Younsoo, thank you for trying PUREE!

Unfortunately, I can't seem to reproduce your error with the data we have. Both the API and the website seem to work well on our side. Does this persist on multiple tries? In addition, do you mind trying the web service directly (https://puree.genome.sg/) to see whether it works for you?

Best,
Egor

**Comment by younsoo4883** [comment] 2023-06-21 04:42
Dear Egor

Hi, thanks for the reply.
I've tried multiple times of your web service (https://puree.genome.sg/),
and it is running forever and not moving onto the next page.
My example input file looks like below, and I set ENSEMBL for gene
identifier type.
Could it be a problem with the network on our side?
Thanks for your help.


[image: image.png]

[image: image.png]


Best regards,
Younsoo Kang


2023년 6월 20일 (화) 오후 2:09, Egor Revkov ***@***.***>님이 작성:

**Comment by younsoo4883** [comment] 2023-06-21 04:45
Dear Egor

Hi, thanks for the reply.
I've tried multiple times of your web service (https://puree.genome.sg/),
and it is running forever and not moving onto the next page.
My example input file "PUREE_input.txt" looks like below, and I set ENSEMBL for gene
identifier type.


<img width="293" alt="image" src="https://github.com/skandlab/PUREE/assets/75415666/f682d466-c711-4f2f-8326-c0c4dc9553f0">

Could it be a problem with the network on our side?
Thanks for your help.

Best regards,
Younsoo Kang

**Comment by younsoo4883** [comment] 2023-06-26 01:39
<img width="828" alt="image" src="https://github.com/skandlab/PUREE/assets/75415666/07792c32-4328-4d1f-84fb-b9bf2621593d">
<img width="1082" alt="image" src="https://github.com/skandlab/PUREE/assets/75415666/4e9e8949-7ec2-41e8-97b3-bc79cad8a016">

Hi, I've tried with .csv file as well, and got above responses.
I'm wondering if the tuple output (<Response [200]>, None) is normal when processing p.submit_file(FILE_PATH) function?

**Comment by tanmay2893** [comment] 2023-06-26 07:45
Dear Younsoo,

Thank you for reaching out to us and bringing the bug to our attention. We sincerely appreciate your contribution in helping us identify and resolve issues, as it greatly contributes to enhancing the overall user experience.

We have addressed the reported bug and have thoroughly tested it on our data. The fix has been implemented to ensure that the expected behavior is exhibited. We kindly request you to retry accessing both the web version and the PUREE API. While we believe that this resolution should resolve the bug you are facing as well, we understand that unexpected issues may still arise. If you encounter any further errors or difficulties, please do not hesitate to inform us. We will be more than happy to assist you in resolving them.

Regarding your comment about the `submit_file` function and its output of `(<Response [200]>, None)`, we would like to clarify that this function serves as an internal component utilized by the final function. The output you mentioned is indeed the expected behavior, as it undergoes additional processing and is instrumental in generating the accurate final output.

Once again, we extend our gratitude for your valuable feedback. If you have any additional questions or require further assistance, please feel free to reach out to us. We are here to help.

Best Regards,
Tanmay

**Comment by younsoo4883** [comment] 2023-06-27 02:16
Dear Tanmay

Hi, I appreciate for your valuable feedback.
However, I still got the same internal server error until now.
Do you have any further idea?

Best,
Younsoo Kang

**Comment by tanmay2893** [comment] 2023-06-27 04:59
Dear Younsoo,

I would like to inquire if you have reinstalled the package on your system by pulling from git again. Since there have been recent changes made to the package, it is essential to reinstall it in order to apply these updates. Additionally, could you also kindly provide the output you received from the website - Is it still running infinitely without any output?

Best regards,
Tanmay

**Comment by younsoo4883** [comment] 2023-06-27 07:09
Dear Tanmay

Hi, I've already re-git clone the whole package, and got the same internal server error as above figure I attached. 
I just tried once again with either .csv file and .tsv file, and it didn't work.
There was no error during installation procedure.
Thanks for your help!

<img width="824" alt="image" src="https://github.com/skandlab/PUREE/assets/75415666/f1d655a8-cfc1-421e-81c5-f1b2b46abe02">


Best,
Younsoo Kang

**Comment by tanmay2893** [comment] 2023-06-27 07:42
Dear Younsoo,

I kindly request you to give the API another try. Additionally, it would be greatly appreciated if you could also test the website using the same data. It will provide us with a better understanding of the bug and aid in its resolution.

Thank you for your cooperation.

Best regards,
Tanmay

**Comment by younsoo4883** [comment] 2023-06-27 07:46
Dear Tanmay

Hi, I tried with .csv file and both API and website work!

<img width="824" alt="image" src="https://github.com/skandlab/PUREE/assets/75415666/a9acd754-30dd-4b25-964c-a5b749796f74">
<img width="452" alt="image" src="https://github.com/skandlab/PUREE/assets/75415666/784ce0e3-b927-4922-91ed-3579e541950a">

I appreciated for your help!

Best,
Younsoo Kang

**Comment by erevkov** [comment] 2023-07-03 04:11
Glad to hear this was solved. Closing it for now, but feel free to reopen if there are any further questions.

**Closed by erevkov** 2023-07-03 04:11 UTC
